name: Continuos Delivery

on:
  push:
jobs:

  puhs_to_docker_hub:

    runs-on: ubuntu-latest
    steps:

        -     name: "Imprimir "
              run: echio "ola mundo"
        -     name: Step 2
              run: echo "teste xpto"