name: Continuos Delivery

on:
  push:
jobs:

  push_to_docker_hub:

    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        -     name: "Imprimir "
              run: echo "ola mundo"
        -     name: Step 2
              run: |
                echo "teste xpto"